*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 20 13:56:59 2021] ***
compiled with version: 9.3.0 on 09 January 2021 18:38:09
os: Linux-5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/yusheng/anaconda3/envs/hus38_env/blog
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
your processes number limit is 12600
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
Set PythonHome to /home/yusheng/anaconda3/envs/hus38_env/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55ecfdeb26a0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55ecfdeb26a0 pid: 105382 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 105382)
spawned uWSGI worker 1 (pid: 105385, cores: 1)
spawned uWSGI worker 2 (pid: 105386, cores: 1)
spawned uWSGI worker 3 (pid: 105387, cores: 1)
spawned uWSGI worker 4 (pid: 105388, cores: 1)
spawned uWSGI worker 5 (pid: 105389, cores: 1)
spawned uWSGI worker 6 (pid: 105390, cores: 1)
spawned uWSGI worker 7 (pid: 105391, cores: 1)
spawned uWSGI worker 8 (pid: 105392, cores: 1)
spawned uWSGI worker 9 (pid: 105393, cores: 1)
spawned uWSGI worker 10 (pid: 105394, cores: 1)
[pid: 105394|app: 0|req: 1/1] 192.168.1.103 () {44 vars in 1358 bytes} [Wed Jan 20 21:58:43 2021] GET / => generated 19157 bytes in 258 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 20 14:06:09 2021] ***
compiled with version: 9.3.0 on 09 January 2021 18:38:09
os: Linux-5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/yusheng/anaconda3/envs/hus38_env/blog
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
your processes number limit is 12600
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
Set PythonHome to /home/yusheng/anaconda3/envs/hus38_env/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55b2af91b6a0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55b2af91b6a0 pid: 105438 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 105438)
spawned uWSGI worker 1 (pid: 105440, cores: 1)
spawned uWSGI worker 2 (pid: 105441, cores: 1)
spawned uWSGI worker 3 (pid: 105442, cores: 1)
spawned uWSGI worker 4 (pid: 105443, cores: 1)
spawned uWSGI worker 5 (pid: 105444, cores: 1)
spawned uWSGI worker 6 (pid: 105445, cores: 1)
spawned uWSGI worker 7 (pid: 105446, cores: 1)
spawned uWSGI worker 8 (pid: 105447, cores: 1)
spawned uWSGI worker 9 (pid: 105448, cores: 1)
spawned uWSGI worker 10 (pid: 105449, cores: 1)
[pid: 105449|app: 0|req: 1/1] 192.168.1.103 () {44 vars in 1365 bytes} [Wed Jan 20 22:07:19 2021] GET / => generated 19157 bytes in 258 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105448|app: 0|req: 1/2] 192.168.1.103 () {44 vars in 1387 bytes} [Wed Jan 20 22:07:38 2021] GET /posts/8/ => generated 13030 bytes in 296 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 2/3] 192.168.1.103 () {44 vars in 1358 bytes} [Wed Jan 20 23:54:36 2021] GET / => generated 19309 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105448|app: 0|req: 2/4] 192.168.1.103 () {44 vars in 1371 bytes} [Wed Jan 20 23:54:39 2021] GET / => generated 19309 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /category.get_absolute_url
[pid: 105449|app: 0|req: 3/5] 192.168.1.103 () {44 vars in 1421 bytes} [Wed Jan 20 23:54:41 2021] GET /category.get_absolute_url => generated 3128 bytes in 10 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /category.get_absolute_url
[pid: 105449|app: 0|req: 4/6] 192.168.1.103 () {48 vars in 1474 bytes} [Wed Jan 20 23:54:48 2021] GET /category.get_absolute_url => generated 3128 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 105449|app: 0|req: 5/7] 192.168.1.103 () {46 vars in 1351 bytes} [Wed Jan 20 23:54:48 2021] GET /favicon.ico => generated 3086 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /categorys/1
[pid: 105447|app: 0|req: 1/8] 192.168.1.103 () {42 vars in 1356 bytes} [Wed Jan 20 23:55:51 2021] GET /categorys/1 => generated 3086 bytes in 41 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /categores/1
[pid: 105449|app: 0|req: 6/9] 192.168.1.103 () {42 vars in 1356 bytes} [Wed Jan 20 23:56:13 2021] GET /categores/1 => generated 3086 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 2/10] 192.168.1.103 () {42 vars in 1358 bytes} [Wed Jan 20 23:56:33 2021] GET /categories/1 => generated 0 bytes in 3 msecs (HTTP/1.1 301) 3 headers in 119 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 3/11] 192.168.1.103 () {42 vars in 1360 bytes} [Wed Jan 20 23:56:33 2021] GET /categories/1/ => generated 11142 bytes in 190 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 7/12] 192.168.1.103 () {44 vars in 1391 bytes} [Wed Jan 20 23:59:32 2021] GET /categories/1/ => generated 11096 bytes in 45 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 8/13] 192.168.1.103 () {44 vars in 1410 bytes} [Wed Jan 20 23:59:34 2021] GET /categories/1/ => generated 11096 bytes in 47 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 4/14] 192.168.1.103 () {44 vars in 1410 bytes} [Wed Jan 20 23:59:43 2021] GET /categories/1/ => generated 11096 bytes in 43 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 9/15] 192.168.1.103 () {44 vars in 1384 bytes} [Wed Jan 20 23:59:45 2021] GET / => generated 19125 bytes in 80 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 5/16] 192.168.1.103 () {44 vars in 1371 bytes} [Wed Jan 20 23:59:50 2021] GET / => generated 19125 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 10/17] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 00:00:00 2021] GET / => generated 19125 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 11/18] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 00:00:09 2021] GET / => generated 19125 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 12/19] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 00:00:11 2021] GET / => generated 19125 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 13/20] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:00:13 2021] GET / => generated 19125 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 14/21] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:00:14 2021] GET / => generated 19125 bytes in 79 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 15/22] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:00:14 2021] GET / => generated 19125 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105446|app: 0|req: 1/23] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:00:27 2021] GET / => generated 19125 bytes in 287 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 16/24] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 00:00:29 2021] GET / => generated 19125 bytes in 85 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 6/25] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 00:00:31 2021] GET / => generated 19125 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 17/26] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:01:36 2021] GET / => generated 19197 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 18/27] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 00:01:41 2021] GET /posts/8/ => generated 13027 bytes in 112 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 19/28] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 00:02:50 2021] GET / => generated 19125 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 20/29] 192.168.1.103 () {46 vars in 1410 bytes} [Thu Jan 21 00:02:52 2021] GET / => generated 19125 bytes in 75 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 21/30] 192.168.1.103 () {46 vars in 1410 bytes} [Thu Jan 21 00:02:52 2021] GET / => generated 19125 bytes in 75 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105448|app: 0|req: 3/31] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 00:02:55 2021] GET / => generated 19125 bytes in 86 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105446|app: 0|req: 2/32] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:04:10 2021] GET / => generated 19125 bytes in 85 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 22/33] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:04:18 2021] GET / => generated 19125 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 23/34] 192.168.1.103 () {48 vars in 1424 bytes} [Thu Jan 21 00:04:19 2021] GET / => generated 19125 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 105449|app: 0|req: 24/35] 192.168.1.103 () {46 vars in 1326 bytes} [Thu Jan 21 00:04:20 2021] GET /favicon.ico => generated 3086 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 25/36] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 00:04:28 2021] GET / => generated 19125 bytes in 75 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 26/37] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 00:04:32 2021] GET / => generated 19125 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 27/38] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:26:30 2021] GET / => generated 19141 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /1
[pid: 105449|app: 0|req: 28/39] 192.168.1.103 () {44 vars in 1373 bytes} [Thu Jan 21 00:26:33 2021] GET /1 => generated 3056 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 7/40] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 00:28:14 2021] GET / => generated 19229 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /categories/ 1
[pid: 105448|app: 0|req: 4/41] 192.168.1.103 () {44 vars in 1399 bytes} [Thu Jan 21 00:28:19 2021] GET /categories/%201 => generated 3094 bytes in 10 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /categories/ 5
[pid: 105449|app: 0|req: 29/42] 192.168.1.103 () {44 vars in 1399 bytes} [Thu Jan 21 00:28:50 2021] GET /categories/%205 => generated 3094 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 30/43] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:33:18 2021] GET / => generated 19245 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /categories/
[pid: 105446|app: 0|req: 3/44] 192.168.1.103 () {44 vars in 1393 bytes} [Thu Jan 21 00:33:23 2021] GET /categories/ => generated 3086 bytes in 9 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 12, in index
    return render(request, 'blog/index.html', context={'post_list': post_list})
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':post.category.pk' from 'int:post.category.pk'
[pid: 105447|app: 0|req: 8/45] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:34:16 2021] GET / => generated 187359 bytes in 183 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 12, in index
    return render(request, 'blog/index.html', context={'post_list': post_list})
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '<int:post.category.pk>' from '<int:post.category.pk>'
[pid: 105449|app: 0|req: 31/46] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:34:42 2021] GET / => generated 186790 bytes in 184 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 12, in index
    return render(request, 'blog/index.html', context={'post_list': post_list})
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':post.category.pk' from 'int:post.category.pk'
[pid: 105448|app: 0|req: 5/47] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:35:15 2021] GET / => generated 187359 bytes in 179 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 12, in index
    return render(request, 'blog/index.html', context={'post_list': post_list})
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':post.category.pk' from 'int:post.category.pk'
[pid: 105449|app: 0|req: 32/48] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:35:18 2021] GET / => generated 187359 bytes in 173 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 12, in index
    return render(request, 'blog/index.html', context={'post_list': post_list})
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':post.category.pk' from 'int:post.category.pk'
[pid: 105449|app: 0|req: 33/49] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:35:27 2021] GET / => generated 187359 bytes in 175 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 12, in index
    return render(request, 'blog/index.html', context={'post_list': post_list})
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':post.category.pk' from 'int:post.category.pk'
[pid: 105449|app: 0|req: 34/50] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:35:27 2021] GET / => generated 187359 bytes in 173 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 35/51] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 00:35:53 2021] GET / => generated 19221 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 36/52] 192.168.1.103 () {44 vars in 1397 bytes} [Thu Jan 21 00:36:03 2021] GET /categories/1/ => generated 11120 bytes in 42 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /categories/1/categories/1
[pid: 105449|app: 0|req: 37/53] 192.168.1.103 () {44 vars in 1434 bytes} [Thu Jan 21 00:36:08 2021] GET /categories/1/categories/1 => generated 3128 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /categories/1/categories/1
[pid: 105449|app: 0|req: 38/54] 192.168.1.103 () {44 vars in 1434 bytes} [Thu Jan 21 00:36:28 2021] GET /categories/1/categories/1 => generated 3128 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 39/55] 192.168.1.103 () {44 vars in 1384 bytes} [Thu Jan 21 00:36:33 2021] GET / => generated 19221 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 40/56] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 00:36:37 2021] GET /categories/3 => generated 0 bytes in 2 msecs (HTTP/1.1 301) 3 headers in 119 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 41/57] 192.168.1.103 () {44 vars in 1397 bytes} [Thu Jan 21 00:36:37 2021] GET /categories/3/ => generated 11056 bytes in 41 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /categories/3/categories/3
[pid: 105449|app: 0|req: 42/58] 192.168.1.103 () {44 vars in 1434 bytes} [Thu Jan 21 00:36:41 2021] GET /categories/3/categories/3 => generated 3128 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /categories/3/categories/3
[pid: 105449|app: 0|req: 43/59] 192.168.1.103 () {46 vars in 1465 bytes} [Thu Jan 21 00:39:07 2021] GET /categories/3/categories/3 => generated 3128 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 12, in index
    return render(request, 'blog/index.html', context={'post_list': post_list})
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':category' from 'blog:category'
[pid: 105449|app: 0|req: 44/60] 192.168.1.103 () {44 vars in 1384 bytes} [Thu Jan 21 00:39:11 2021] GET / => generated 187202 bytes in 172 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 45/61] 192.168.1.103 () {46 vars in 1415 bytes} [Thu Jan 21 00:39:47 2021] GET / => generated 19133 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 46/62] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 00:39:49 2021] GET / => generated 19133 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /1
[pid: 105449|app: 0|req: 47/63] 192.168.1.103 () {44 vars in 1373 bytes} [Thu Jan 21 01:34:09 2021] GET /1 => generated 3056 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /1
[pid: 105447|app: 0|req: 9/64] 192.168.1.103 () {46 vars in 1404 bytes} [Thu Jan 21 01:36:20 2021] GET /1 => generated 3056 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 105448|app: 0|req: 6/65] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 01:36:26 2021] GET / => generated 19133 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 105449|app: 0|req: 48/66] 192.168.1.103 () {42 vars in 1273 bytes} [Thu Jan 21 12:42:30 2021] GET /favicon.ico => generated 3086 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 10/67] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 12:42:33 2021] GET / => generated 19133 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /1
[pid: 105449|app: 0|req: 49/68] 192.168.1.103 () {44 vars in 1373 bytes} [Thu Jan 21 12:42:38 2021] GET /1 => generated 3056 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 12, in index
    return render(request, 'blog/index.html', context={'post_list': post_list})
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/resolvers.py", line 668, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'category' with no arguments not found. 1 pattern(s) tried: ['categories/(?P<pk>[0-9]+)/$']
[pid: 105449|app: 0|req: 50/69] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 12:48:17 2021] GET / => generated 171078 bytes in 160 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 51/70] 192.168.1.103 () {46 vars in 1428 bytes} [Thu Jan 21 12:50:12 2021] GET /categories/3/ => generated 11060 bytes in 42 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 52/71] 192.168.1.103 () {44 vars in 1384 bytes} [Thu Jan 21 12:50:14 2021] GET / => generated 19237 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 53/72] 192.168.1.103 () {44 vars in 1397 bytes} [Thu Jan 21 12:50:24 2021] GET /categories/1/ => generated 11124 bytes in 42 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 54/73] 192.168.1.103 () {44 vars in 1410 bytes} [Thu Jan 21 12:50:30 2021] GET /categories/1/ => generated 11124 bytes in 42 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 55/74] 192.168.1.103 () {44 vars in 1384 bytes} [Thu Jan 21 12:50:33 2021] GET / => generated 19237 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 56/75] 192.168.1.103 () {44 vars in 1397 bytes} [Thu Jan 21 12:50:39 2021] GET /categories/3/ => generated 11060 bytes in 42 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105448|app: 0|req: 7/76] 192.168.1.103 () {44 vars in 1384 bytes} [Thu Jan 21 12:51:52 2021] GET / => generated 19237 bytes in 79 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105446|app: 0|req: 4/77] 192.168.1.103 () {44 vars in 1403 bytes} [Thu Jan 21 12:52:37 2021] GET /archives/2021/1/ => generated 19237 bytes in 82 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 57/78] 192.168.1.103 () {44 vars in 1413 bytes} [Thu Jan 21 12:52:44 2021] GET /categories/4/ => generated 9660 bytes in 39 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 58/79] 192.168.1.103 () {46 vars in 1444 bytes} [Thu Jan 21 13:04:02 2021] GET /categories/4/ => generated 9660 bytes in 36 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 59/80] 192.168.1.103 () {44 vars in 1384 bytes} [Thu Jan 21 13:04:05 2021] GET / => generated 19237 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 60/81] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:04:19 2021] GET /posts/8/ => generated 13027 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 61/82] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 13:04:22 2021] GET / => generated 19237 bytes in 75 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Internal Server Error: /posts/2/
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 25, in detail
    post.increase_views()
AttributeError: 'Post' object has no attribute 'increase_views'
[pid: 105447|app: 0|req: 11/83] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:06:38 2021] GET /posts/2/ => generated 60811 bytes in 129 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 62/84] 192.168.1.103 () {46 vars in 1410 bytes} [Thu Jan 21 13:12:38 2021] GET / => generated 19237 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 63/85] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:12:40 2021] GET /posts/8/ => generated 13027 bytes in 62 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 64/86] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 13:13:03 2021] GET / => generated 19237 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 65/87] 192.168.1.103 () {44 vars in 1397 bytes} [Thu Jan 21 13:13:06 2021] GET /categories/1/ => generated 11124 bytes in 42 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 66/88] 192.168.1.103 () {44 vars in 1400 bytes} [Thu Jan 21 13:13:08 2021] GET /posts/8/ => generated 13027 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 67/89] 192.168.1.103 () {46 vars in 1431 bytes} [Thu Jan 21 13:13:17 2021] GET /posts/8/ => generated 13027 bytes in 62 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 68/90] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 13:13:24 2021] GET / => generated 19237 bytes in 75 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 69/91] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:13:26 2021] GET /posts/8/ => generated 13027 bytes in 62 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 70/92] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 13:20:23 2021] GET / => generated 19237 bytes in 75 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 71/93] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:20:25 2021] GET /posts/8/ => generated 13039 bytes in 62 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 72/94] 192.168.1.103 () {52 vars in 1580 bytes} [Thu Jan 21 13:21:23 2021] POST /comment/8 => generated 0 bytes in 21 msecs (HTTP/1.1 302) 5 headers in 335 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 73/95] 192.168.1.103 () {46 vars in 1585 bytes} [Thu Jan 21 13:21:23 2021] GET /posts/8/ => generated 13575 bytes in 63 msecs (HTTP/1.1 200) 6 headers in 377 bytes (1 switches on core 0)
Internal Server Error: /posts/8/
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 25, in detail
    post.increase_views()
AttributeError: 'Post' object has no attribute 'increase_views'
[pid: 105447|app: 0|req: 12/96] 192.168.1.103 () {46 vars in 1426 bytes} [Thu Jan 21 13:27:52 2021] GET /posts/8/ => generated 60965 bytes in 92 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 74/97] 192.168.1.103 () {44 vars in 1358 bytes} [Thu Jan 21 13:28:04 2021] GET / => generated 19277 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 75/98] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 13:28:08 2021] GET / => generated 19277 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 76/99] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:28:11 2021] GET /posts/8/ => generated 13333 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 77/100] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 13:28:18 2021] GET /posts/8/ => generated 13333 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 78/101] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 13:28:22 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 79/102] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 13:28:24 2021] GET /posts/5/ => generated 9790 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 80/103] 192.168.1.103 () {44 vars in 1405 bytes} [Thu Jan 21 13:28:31 2021] GET /categories/1/ => generated 11164 bytes in 43 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 81/104] 192.168.1.103 () {44 vars in 1410 bytes} [Thu Jan 21 13:28:33 2021] GET /categories/4/ => generated 9700 bytes in 36 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 82/105] 192.168.1.103 () {44 vars in 1384 bytes} [Thu Jan 21 13:28:35 2021] GET / => generated 19277 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 83/106] 192.168.1.103 () {44 vars in 1385 bytes} [Thu Jan 21 13:28:40 2021] GET /tags/1/ => generated 12507 bytes in 50 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 84/107] 192.168.1.103 () {44 vars in 1378 bytes} [Thu Jan 21 13:29:06 2021] GET / => generated 19277 bytes in 114 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 85/108] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:29:18 2021] GET /posts/4/ => generated 9784 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 12, in index
    return render(request, 'blog/index.html', context={'post_list': post_list})
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' 'blog:category' post.category.pk' from 'url 'blog:category' post.category.pk'
[pid: 105448|app: 0|req: 8/109] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 13:31:46 2021] GET / => generated 181276 bytes in 168 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 86/110] 192.168.1.103 () {46 vars in 1410 bytes} [Thu Jan 21 13:34:24 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 13/111] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 13:34:25 2021] GET / => generated 19341 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 87/112] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:34:27 2021] GET /posts/8/ => generated 13333 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 14/113] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 13:34:29 2021] GET / => generated 19341 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 88/114] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:34:32 2021] GET /posts/8/ => generated 13333 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 89/115] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 13:34:35 2021] GET / => generated 19341 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 90/116] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:34:39 2021] GET /posts/7/ => generated 9763 bytes in 57 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 91/117] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 13:34:48 2021] GET / => generated 19341 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 92/118] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:34:51 2021] GET /posts/6/ => generated 9747 bytes in 55 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 93/119] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 13:34:54 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 94/120] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 13:34:56 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 95/121] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 13:34:58 2021] GET /posts/8/ => generated 13333 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 96/122] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 13:35:02 2021] GET /posts/8/ => generated 13333 bytes in 65 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 97/123] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 13:35:29 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 98/124] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 13:35:44 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 99/125] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 13:35:48 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 100/126] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 14:00:04 2021] GET /posts/8/ => generated 13333 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 101/127] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 14:00:05 2021] GET / => generated 19341 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 102/128] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 14:00:07 2021] GET / => generated 19341 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 103/129] 192.168.1.103 () {44 vars in 1397 bytes} [Thu Jan 21 14:00:10 2021] GET /categories/1/ => generated 11180 bytes in 43 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 104/130] 192.168.1.103 () {44 vars in 1400 bytes} [Thu Jan 21 14:00:15 2021] GET /posts/8/ => generated 13333 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 105/131] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 14:00:19 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 106/132] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 14:38:27 2021] GET / => generated 19341 bytes in 79 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 107/133] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 14:38:28 2021] GET /posts/8/ => generated 13333 bytes in 68 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
Internal Server Error: /posts/8/
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 25, in detail
    def detail(request, pk):
AttributeError: 'Post' object has no attribute 'increase_views'
[pid: 105447|app: 0|req: 15/134] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 14:38:32 2021] GET /posts/8/ => generated 60898 bytes in 88 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 108/135] 192.168.1.103 () {44 vars in 1358 bytes} [Thu Jan 21 14:39:02 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 109/136] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 14:39:06 2021] GET /posts/8/ => generated 13333 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 110/137] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 14:39:07 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 111/138] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 14:39:09 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 112/139] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 14:39:12 2021] GET /posts/8/ => generated 13333 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 113/140] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 14:39:14 2021] GET /posts/8/ => generated 13333 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 114/141] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 14:39:16 2021] GET /posts/8/ => generated 13333 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 115/142] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 14:39:17 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 116/143] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 14:39:19 2021] GET / => generated 19341 bytes in 79 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 117/144] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 14:39:30 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 118/145] 192.168.1.103 () {44 vars in 1405 bytes} [Thu Jan 21 14:39:34 2021] GET /categories/3/ => generated 11116 bytes in 43 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 119/146] 192.168.1.103 () {44 vars in 1400 bytes} [Thu Jan 21 14:39:38 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 120/147] 192.168.1.103 () {44 vars in 1405 bytes} [Thu Jan 21 14:39:40 2021] GET /categories/3/ => generated 11116 bytes in 42 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 121/148] 192.168.1.103 () {44 vars in 1400 bytes} [Thu Jan 21 14:39:42 2021] GET /posts/3/ => generated 9797 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 122/149] 192.168.1.103 () {44 vars in 1405 bytes} [Thu Jan 21 14:39:47 2021] GET /categories/5/ => generated 11078 bytes in 43 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 123/150] 192.168.1.103 () {44 vars in 1400 bytes} [Thu Jan 21 14:39:49 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 124/151] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 14:39:51 2021] GET /posts/6/ => generated 9747 bytes in 57 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 125/152] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 14:39:53 2021] GET /posts/8/ => generated 13333 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 126/153] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 14:39:58 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 127/154] 192.168.1.103 () {46 vars in 1426 bytes} [Thu Jan 21 14:40:07 2021] GET /posts/7/ => generated 9763 bytes in 55 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 128/155] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 14:40:08 2021] GET /posts/8/ => generated 13333 bytes in 62 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 129/156] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 14:40:10 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 130/157] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 14:40:35 2021] GET /posts/8/ => generated 13333 bytes in 65 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 131/158] 192.168.1.103 () {44 vars in 1358 bytes} [Thu Jan 21 15:03:14 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 132/159] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 15:03:16 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 133/160] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 15:03:22 2021] GET /posts/8/ => generated 13333 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 134/161] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 15:03:25 2021] GET /posts/8/ => generated 13333 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 135/162] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 15:03:27 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 136/163] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 15:03:32 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 137/164] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 15:03:35 2021] GET /posts/8/ => generated 13333 bytes in 62 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 138/165] 192.168.1.103 () {44 vars in 1411 bytes} [Thu Jan 21 15:03:39 2021] GET /archives/2021/1/ => generated 19341 bytes in 81 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 139/166] 192.168.1.103 () {44 vars in 1413 bytes} [Thu Jan 21 15:03:47 2021] GET /categories/1/ => generated 11180 bytes in 42 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 140/167] 192.168.1.103 () {46 vars in 1444 bytes} [Thu Jan 21 15:03:49 2021] GET /categories/1/ => generated 11180 bytes in 42 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 141/168] 192.168.1.103 () {44 vars in 1384 bytes} [Thu Jan 21 15:03:53 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 142/169] 192.168.1.103 () {44 vars in 1403 bytes} [Thu Jan 21 15:04:01 2021] GET /archives/2021/1/ => generated 19341 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 16/170] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 15:06:27 2021] GET / => generated 19341 bytes in 83 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 143/171] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 15:06:28 2021] GET /posts/8/ => generated 13333 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 144/172] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 15:06:30 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 145/173] 192.168.1.103 () {44 vars in 1403 bytes} [Thu Jan 21 15:06:31 2021] GET /archives/2021/1/ => generated 19341 bytes in 80 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 146/174] 192.168.1.103 () {44 vars in 1403 bytes} [Thu Jan 21 15:06:34 2021] GET /posts/8/ => generated 13333 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 147/175] 192.168.1.103 () {44 vars in 1411 bytes} [Thu Jan 21 15:06:36 2021] GET /archives/2021/1/ => generated 19341 bytes in 79 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105448|app: 0|req: 9/176] 192.168.1.103 () {46 vars in 1442 bytes} [Thu Jan 21 15:14:25 2021] GET /archives/2021/1/ => generated 19341 bytes in 82 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 148/177] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 15:14:27 2021] GET / => generated 19341 bytes in 82 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 149/178] 192.168.1.103 () {44 vars in 1403 bytes} [Thu Jan 21 15:14:29 2021] GET /archives/2021/1/ => generated 19341 bytes in 81 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 150/179] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 15:14:31 2021] GET / => generated 19341 bytes in 80 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 151/180] 192.168.1.103 () {44 vars in 1397 bytes} [Thu Jan 21 15:14:37 2021] GET /categories/1/ => generated 11180 bytes in 45 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 152/181] 192.168.1.103 () {44 vars in 1398 bytes} [Thu Jan 21 15:14:44 2021] GET /tags/1/ => generated 12531 bytes in 54 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 17/182] 192.168.1.103 () {44 vars in 1392 bytes} [Thu Jan 21 15:14:58 2021] GET /tags/2/ => generated 11074 bytes in 44 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105448|app: 0|req: 10/183] 192.168.1.103 () {44 vars in 1392 bytes} [Thu Jan 21 15:15:11 2021] GET /tags/3/ => generated 9757 bytes in 37 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 153/184] 192.168.1.103 () {44 vars in 1392 bytes} [Thu Jan 21 15:15:15 2021] GET /tags/4/ => generated 9708 bytes in 36 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 154/185] 192.168.1.103 () {44 vars in 1392 bytes} [Thu Jan 21 15:15:19 2021] GET /tags/5/ => generated 9721 bytes in 36 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 155/186] 192.168.1.103 () {46 vars in 1423 bytes} [Thu Jan 21 15:33:59 2021] GET /tags/5/ => generated 9721 bytes in 37 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 156/187] 192.168.1.103 () {44 vars in 1378 bytes} [Thu Jan 21 15:34:01 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 157/188] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 15:34:05 2021] GET /posts/8/ => generated 13333 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 158/189] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 15:34:13 2021] GET /posts/8/ => generated 13333 bytes in 65 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 159/190] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 15:34:16 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 160/191] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 15:34:17 2021] GET /posts/3/ => generated 9797 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 161/192] 192.168.1.103 () {44 vars in 1405 bytes} [Thu Jan 21 15:34:20 2021] GET /categories/3/ => generated 11116 bytes in 42 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 162/193] 192.168.1.103 () {44 vars in 1400 bytes} [Thu Jan 21 15:34:23 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 163/194] 192.168.1.103 () {44 vars in 1405 bytes} [Thu Jan 21 15:34:26 2021] GET /categories/4/ => generated 9708 bytes in 37 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 164/195] 192.168.1.103 () {44 vars in 1400 bytes} [Thu Jan 21 15:34:29 2021] GET /posts/4/ => generated 9784 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 165/196] 192.168.1.103 () {44 vars in 1393 bytes} [Thu Jan 21 15:34:33 2021] GET /tags/2/ => generated 11074 bytes in 43 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 166/197] 192.168.1.103 () {44 vars in 1394 bytes} [Thu Jan 21 15:34:37 2021] GET /posts/7/ => generated 9763 bytes in 58 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 167/198] 192.168.1.103 () {46 vars in 1425 bytes} [Thu Jan 21 16:08:51 2021] GET /posts/7/ => generated 9763 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 168/199] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 16:08:53 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 169/200] 192.168.1.103 () {46 vars in 1410 bytes} [Thu Jan 21 16:24:49 2021] GET / => generated 19341 bytes in 82 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 18/201] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 16:24:52 2021] GET / => generated 19341 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 170/202] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 21:41:59 2021] GET / => generated 19341 bytes in 79 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105448|app: 0|req: 11/203] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 21:42:04 2021] GET / => generated 19341 bytes in 80 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Internal Server Error: /posts/8/
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./blog/views.py", line 25, in detail
    class TagView(IndexView):
AttributeError: 'Post' object has no attribute 'increase_views'
[pid: 105446|app: 0|req: 5/204] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 21:42:05 2021] GET /posts/8/ => generated 60894 bytes in 137 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 171/205] 192.168.1.103 () {44 vars in 1358 bytes} [Thu Jan 21 21:42:28 2021] GET / => generated 19341 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 172/206] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 21:42:31 2021] GET /posts/8/ => generated 13333 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 173/207] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 21:42:34 2021] GET / => generated 19341 bytes in 77 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 174/208] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 21:42:37 2021] GET /posts/8/ => generated 13333 bytes in 65 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 175/209] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 21:42:46 2021] GET /posts/8/ => generated 13333 bytes in 100 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 176/210] 192.168.1.103 () {44 vars in 1395 bytes} [Thu Jan 21 21:42:48 2021] GET /posts/8/ => generated 13333 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 177/211] 192.168.1.103 () {44 vars in 1411 bytes} [Thu Jan 21 21:42:51 2021] GET /archives/2021/1/ => generated 19341 bytes in 79 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 178/212] 192.168.1.103 () {44 vars in 1401 bytes} [Thu Jan 21 21:42:53 2021] GET /tags/1/ => generated 12531 bytes in 49 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /tags/1/
[pid: 105449|app: 0|req: 179/213] 192.168.1.103 () {46 vars in 1432 bytes} [Thu Jan 21 22:00:58 2021] GET /tags/1/ => generated 1715 bytes in 9 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 19/214] 192.168.1.103 () {42 vars in 1334 bytes} [Thu Jan 21 22:01:05 2021] GET / => generated 307701 bytes in 1265 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 180/215] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 22:01:17 2021] GET /posts/9/ => generated 33447 bytes in 1731 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
Not Found: /posts/9/example.jpg
[pid: 105447|app: 0|req: 20/216] 192.168.1.103 () {42 vars in 1297 bytes} [Thu Jan 21 22:01:19 2021] GET /posts/9/example.jpg => generated 3110 bytes in 9 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Internal Server Error: /posts/9/a.jpg
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/resolvers.py", line 535, in resolve
    for pattern in self.url_patterns:
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogproject/urls.py", line 21, in <module>
    path('', include('blog.urls')),
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blog/urls.py", line 9, in <module>
    path('posts/<int:pk>/', DetailView.as_view(), name='detail'),
NameError: name 'DetailView' is not defined
[pid: 105441|app: 0|req: 1/217] 192.168.1.103 () {42 vars in 1285 bytes} [Thu Jan 21 22:01:19 2021] GET /posts/9/a.jpg => generated 154658 bytes in 278 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
[pid: 105448|app: 0|req: 12/218] 192.168.1.103 () {44 vars in 1405 bytes} [Thu Jan 21 22:01:36 2021] GET /categories/6/ => generated 64072 bytes in 259 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 181/219] 192.168.1.103 () {44 vars in 1400 bytes} [Thu Jan 21 22:01:55 2021] GET /posts/9/ => generated 33447 bytes in 172 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
Not Found: /posts/9/example.jpg
[pid: 105449|app: 0|req: 182/220] 192.168.1.103 () {42 vars in 1297 bytes} [Thu Jan 21 22:01:55 2021] GET /posts/9/example.jpg => generated 3110 bytes in 9 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Internal Server Error: /posts/9/a.jpg
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/resolvers.py", line 535, in resolve
    for pattern in self.url_patterns:
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogproject/urls.py", line 21, in <module>
    path('', include('blog.urls')),
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blog/urls.py", line 9, in <module>
    path('posts/<int:pk>/', DetailView.as_view(), name='detail'),
NameError: name 'DetailView' is not defined
[pid: 105444|app: 0|req: 1/221] 192.168.1.103 () {42 vars in 1285 bytes} [Thu Jan 21 22:01:55 2021] GET /posts/9/a.jpg => generated 154658 bytes in 267 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 183/222] 192.168.1.103 () {44 vars in 1411 bytes} [Thu Jan 21 22:03:46 2021] GET /archives/2020/9/ => generated 24873 bytes in 108 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 184/223] 192.168.1.103 () {44 vars in 1413 bytes} [Thu Jan 21 22:06:21 2021] GET /categories/6/ => generated 64072 bytes in 258 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 185/224] 192.168.1.103 () {44 vars in 1404 bytes} [Thu Jan 21 22:06:30 2021] GET /posts/168/ => generated 15484 bytes in 72 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 186/225] 192.168.1.103 () {44 vars in 1407 bytes} [Thu Jan 21 22:06:48 2021] GET /categories/6/ => generated 64072 bytes in 257 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 187/226] 192.168.1.103 () {44 vars in 1404 bytes} [Thu Jan 21 22:06:50 2021] GET /posts/209/ => generated 15929 bytes in 72 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 188/227] 192.168.1.103 () {44 vars in 1381 bytes} [Thu Jan 21 22:06:55 2021] GET / => generated 307701 bytes in 1258 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 189/228] 192.168.1.103 () {44 vars in 1403 bytes} [Thu Jan 21 22:07:04 2021] GET /archives/2020/7/ => generated 35210 bytes in 151 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 190/229] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 22:07:20 2021] GET / => generated 307701 bytes in 1256 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 191/230] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 22:43:25 2021] GET / => generated 307701 bytes in 1257 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 192/231] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 22:43:37 2021] GET / => generated 307701 bytes in 1255 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 193/232] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 22:43:45 2021] GET / => generated 307701 bytes in 1338 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 194/233] 192.168.1.103 () {44 vars in 1387 bytes} [Thu Jan 21 22:43:47 2021] GET /posts/9/ => generated 33447 bytes in 167 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
Not Found: /posts/9/a.jpg
[pid: 105449|app: 0|req: 195/234] 192.168.1.103 () {42 vars in 1285 bytes} [Thu Jan 21 22:43:48 2021] GET /posts/9/a.jpg => generated 3092 bytes in 10 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Internal Server Error: /posts/9/example.jpg
Traceback (most recent call last):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/resolvers.py", line 535, in resolve
    for pattern in self.url_patterns:
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogproject/urls.py", line 21, in <module>
    path('', include('blog.urls')),
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blog/urls.py", line 9, in <module>
    path('posts/<int:pk>/', DetailView.as_view(), name='detail'),
NameError: name 'DetailView' is not defined
[pid: 105440|app: 0|req: 1/235] 192.168.1.103 () {42 vars in 1297 bytes} [Thu Jan 21 22:43:48 2021] GET /posts/9/example.jpg => generated 154760 bytes in 278 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 196/236] 192.168.1.103 () {44 vars in 1379 bytes} [Thu Jan 21 22:47:15 2021] GET / => generated 307701 bytes in 1253 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 197/237] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 22:47:31 2021] GET / => generated 307701 bytes in 1252 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 105447|app: 0|req: 21/238] 192.168.1.103 () {44 vars in 1371 bytes} [Thu Jan 21 22:50:39 2021] GET / => generated 307120 bytes in 1255 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 198/239] 192.168.1.103 () {46 vars in 1402 bytes} [Thu Jan 21 22:50:52 2021] GET / => generated 307120 bytes in 1256 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 105449|app: 0|req: 199/240] 192.168.1.103 () {48 vars in 1424 bytes} [Thu Jan 21 22:50:54 2021] GET / => generated 307120 bytes in 1255 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 105449|app: 0|req: 200/241] 192.168.1.103 () {46 vars in 1326 bytes} [Thu Jan 21 22:50:56 2021] GET /favicon.ico => generated 3086 bytes in 11 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Gracefully killing worker 1 (pid: 105440)...
Gracefully killing worker 5 (pid: 105444)...
Gracefully killing worker 8 (pid: 105447)...
Gracefully killing worker 7 (pid: 105446)...
Gracefully killing worker 2 (pid: 105441)...
Gracefully killing worker 10 (pid: 105449)...
Gracefully killing worker 9 (pid: 105448)...
Gracefully killing worker 3 (pid: 105442)...
Gracefully killing worker 4 (pid: 105443)...
Gracefully killing worker 6 (pid: 105445)...
...brutally killing workers...
worker 5 buried after 1 seconds
worker 1 buried after 3 seconds
worker 2 buried after 7 seconds
worker 3 buried after 7 seconds
worker 4 buried after 7 seconds
worker 6 buried after 7 seconds
worker 9 buried after 8 seconds
worker 7 buried after 9 seconds
worker 8 buried after 9 seconds
worker 10 buried after 9 seconds
binary reloading uWSGI...
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:9090)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /home/yusheng/anaconda3/envs/hus38_env/blog/uwsgi.ini
[uwsgi-static] added mapping for /static =>  /home/yusheng/anaconda3/envs/hus38_env/blog/static
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Jan 24 16:00:53 2021] ***
compiled with version: 9.3.0 on 09 January 2021 18:38:09
os: Linux-5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/yusheng/anaconda3/envs/hus38_env/blog
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
your processes number limit is 12600
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:9090 fd 3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
Set PythonHome to /home/yusheng/anaconda3/envs/hus38_env/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5650461871e0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./blogproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 176, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 105438)
spawned uWSGI worker 1 (pid: 130213, cores: 1)
spawned uWSGI worker 2 (pid: 130214, cores: 1)
spawned uWSGI worker 3 (pid: 130215, cores: 1)
spawned uWSGI worker 4 (pid: 130216, cores: 1)
spawned uWSGI worker 5 (pid: 130217, cores: 1)
spawned uWSGI worker 6 (pid: 130218, cores: 1)
spawned uWSGI worker 7 (pid: 130219, cores: 1)
spawned uWSGI worker 8 (pid: 130220, cores: 1)
spawned uWSGI worker 9 (pid: 130221, cores: 1)
spawned uWSGI worker 10 (pid: 130222, cores: 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 27 09:26:45 2021] ***
compiled with version: 9.3.0 on 09 January 2021 18:38:09
os: Linux-5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/yusheng/anaconda3/envs/hus38_env/blog
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
your processes number limit is 12600
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
Set PythonHome to /home/yusheng/anaconda3/envs/hus38_env/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55c284df1750
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./blogproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./blogproject/settings/production.py", line 3, in <module>
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'DJANGO_SECRET_KEY'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5709)
spawned uWSGI worker 1 (pid: 5711, cores: 1)
spawned uWSGI worker 2 (pid: 5712, cores: 1)
spawned uWSGI worker 3 (pid: 5713, cores: 1)
spawned uWSGI worker 4 (pid: 5714, cores: 1)
spawned uWSGI worker 5 (pid: 5715, cores: 1)
spawned uWSGI worker 6 (pid: 5716, cores: 1)
spawned uWSGI worker 7 (pid: 5717, cores: 1)
spawned uWSGI worker 8 (pid: 5718, cores: 1)
spawned uWSGI worker 9 (pid: 5719, cores: 1)
spawned uWSGI worker 10 (pid: 5720, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/1] 192.168.1.103 () {42 vars in 1334 bytes} [Wed Jan 27 09:28:22 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/2] 192.168.1.103 () {42 vars in 1273 bytes} [Wed Jan 27 09:28:22 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/3] 192.168.1.103 () {42 vars in 1334 bytes} [Wed Jan 27 09:29:20 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/4] 192.168.1.103 () {42 vars in 1273 bytes} [Wed Jan 27 09:29:20 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/5] 192.168.1.103 () {42 vars in 1334 bytes} [Wed Jan 27 09:29:44 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/6] 192.168.1.103 () {42 vars in 1273 bytes} [Wed Jan 27 09:29:44 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 27 09:33:34 2021] ***
compiled with version: 9.3.0 on 09 January 2021 18:38:09
os: Linux-5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/yusheng/anaconda3/envs/hus38_env/blog
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
your processes number limit is 12600
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9090).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/7] 192.168.1.103 () {44 vars in 1365 bytes} [Wed Jan 27 09:38:49 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/8] 192.168.1.103 () {46 vars in 1326 bytes} [Wed Jan 27 09:38:50 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/9] 192.168.1.103 () {44 vars in 1365 bytes} [Wed Jan 27 09:38:57 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/10] 192.168.1.103 () {46 vars in 1326 bytes} [Wed Jan 27 09:38:57 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/11] 192.168.1.103 () {44 vars in 1365 bytes} [Wed Jan 27 09:53:15 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/12] 192.168.1.103 () {46 vars in 1326 bytes} [Wed Jan 27 09:53:15 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/13] 192.168.1.103 () {42 vars in 1334 bytes} [Wed Jan 27 09:53:41 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/14] 192.168.1.103 () {42 vars in 1273 bytes} [Wed Jan 27 09:53:41 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/15] 192.168.1.103 () {42 vars in 1273 bytes} [Wed Jan 27 10:01:23 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5713|app: -1|req: -1/16] 192.168.1.103 () {44 vars in 1314 bytes} [Wed Jan 27 12:46:21 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/17] 192.168.1.103 () {42 vars in 1229 bytes} [Wed Jan 27 12:46:22 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/18] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 12:46:26 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/19] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 12:46:26 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/20] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 12:46:27 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/21] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 12:46:27 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/22] 192.168.1.103 () {44 vars in 1314 bytes} [Wed Jan 27 15:14:08 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/23] 192.168.1.103 () {42 vars in 1229 bytes} [Wed Jan 27 15:14:09 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/24] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 15:14:11 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5719|app: -1|req: -1/25] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 15:14:11 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Wed Jan 27 15:15:56 2021 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 27 15:17:19 2021] ***
compiled with version: 9.3.0 on 09 January 2021 18:38:09
os: Linux-5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/yusheng/anaconda3/envs/hus38_env/blog
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
your processes number limit is 12600
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
Set PythonHome to /home/yusheng/anaconda3/envs/hus38_env/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5639c88776a0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./blogproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'blogproject.settings.production'; 'blogproject.settings' is not a package
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7075)
spawned uWSGI worker 1 (pid: 7077, cores: 1)
spawned uWSGI worker 2 (pid: 7078, cores: 1)
spawned uWSGI worker 3 (pid: 7079, cores: 1)
spawned uWSGI worker 4 (pid: 7080, cores: 1)
spawned uWSGI worker 5 (pid: 7081, cores: 1)
spawned uWSGI worker 6 (pid: 7082, cores: 1)
spawned uWSGI worker 7 (pid: 7083, cores: 1)
spawned uWSGI worker 8 (pid: 7084, cores: 1)
spawned uWSGI worker 9 (pid: 7085, cores: 1)
spawned uWSGI worker 10 (pid: 7086, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/1] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 15:18:04 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/2] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 15:18:04 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/3] 192.168.1.103 () {42 vars in 1312 bytes} [Wed Jan 27 15:18:54 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/4] 192.168.1.103 () {42 vars in 1240 bytes} [Wed Jan 27 15:18:54 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/5] 192.168.1.103 () {44 vars in 1343 bytes} [Wed Jan 27 15:19:05 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/6] 192.168.1.103 () {46 vars in 1293 bytes} [Wed Jan 27 15:19:05 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/7] 192.168.1.103 () {42 vars in 1290 bytes} [Wed Jan 27 15:19:34 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/8] 192.168.1.103 () {42 vars in 1229 bytes} [Wed Jan 27 15:19:35 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/9] 192.168.1.103 () {42 vars in 1300 bytes} [Wed Jan 27 15:19:42 2021] GET /sdmin => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/10] 192.168.1.103 () {42 vars in 1234 bytes} [Wed Jan 27 15:19:42 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/11] 192.168.1.103 () {42 vars in 1300 bytes} [Wed Jan 27 15:19:50 2021] GET /admin => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/12] 192.168.1.103 () {42 vars in 1234 bytes} [Wed Jan 27 15:19:50 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/13] 192.168.1.103 () {42 vars in 1290 bytes} [Wed Jan 27 15:23:35 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/14] 192.168.1.103 () {42 vars in 1229 bytes} [Wed Jan 27 15:23:35 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/15] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 15:28:42 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7086|app: -1|req: -1/16] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 15:28:42 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 27 15:34:31 2021] ***
compiled with version: 9.3.0 on 09 January 2021 18:38:09
os: Linux-5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/yusheng/anaconda3/envs/hus38_env/blog
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
your processes number limit is 12600
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
Set PythonHome to /home/yusheng/anaconda3/envs/hus38_env/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x564ea325d6a0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./blogproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'blogproject.settings.production'; 'blogproject.settings' is not a package
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7134)
spawned uWSGI worker 1 (pid: 7136, cores: 1)
spawned uWSGI worker 2 (pid: 7137, cores: 1)
spawned uWSGI worker 3 (pid: 7138, cores: 1)
spawned uWSGI worker 4 (pid: 7139, cores: 1)
spawned uWSGI worker 5 (pid: 7140, cores: 1)
spawned uWSGI worker 6 (pid: 7141, cores: 1)
spawned uWSGI worker 7 (pid: 7142, cores: 1)
spawned uWSGI worker 8 (pid: 7143, cores: 1)
spawned uWSGI worker 9 (pid: 7144, cores: 1)
spawned uWSGI worker 10 (pid: 7145, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/1] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 15:35:23 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/2] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 15:35:23 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/3] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 15:35:25 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/4] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 15:35:25 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7145|app: -1|req: -1/5] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 15:36:53 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/6] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 15:36:53 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 27 16:27:51 2021] ***
compiled with version: 9.3.0 on 09 January 2021 18:38:09
os: Linux-5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/yusheng/anaconda3/envs/hus38_env/blog
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
your processes number limit is 12600
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9090).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/7] 192.168.1.103 () {48 vars in 1413 bytes} [Wed Jan 27 16:35:46 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/8] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 16:35:57 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/9] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 16:36:50 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/10] 192.168.1.103 () {46 vars in 1343 bytes} [Wed Jan 27 16:36:53 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/11] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 16:36:53 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/12] 192.168.1.103 () {42 vars in 1290 bytes} [Wed Jan 27 16:37:10 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/13] 192.168.1.103 () {42 vars in 1229 bytes} [Wed Jan 27 16:37:10 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/14] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 16:37:12 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7145|app: -1|req: -1/15] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 16:37:13 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/16] 192.168.1.103 () {42 vars in 1300 bytes} [Wed Jan 27 16:38:30 2021] GET /admin => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/17] 192.168.1.103 () {42 vars in 1234 bytes} [Wed Jan 27 16:38:30 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/18] 192.168.1.103 () {42 vars in 1290 bytes} [Wed Jan 27 16:38:45 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/19] 192.168.1.103 () {42 vars in 1229 bytes} [Wed Jan 27 16:38:45 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/20] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 16:38:54 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/21] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 16:38:54 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/22] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 16:39:03 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7145|app: -1|req: -1/23] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 16:39:03 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/24] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 16:42:15 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7145|app: -1|req: -1/25] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 16:42:15 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/26] 192.168.1.103 () {46 vars in 1343 bytes} [Wed Jan 27 16:42:17 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/27] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 16:42:17 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/28] 192.168.1.103 () {46 vars in 1343 bytes} [Wed Jan 27 16:42:20 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/29] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 16:42:20 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/30] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 16:47:58 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/31] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 16:47:58 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/32] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 17:49:17 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/33] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 17:49:17 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7143|app: -1|req: -1/34] 192.168.1.103 () {44 vars in 1314 bytes} [Wed Jan 27 17:51:53 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/35] 192.168.1.103 () {42 vars in 1229 bytes} [Wed Jan 27 17:51:53 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/36] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 17:51:57 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/37] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 17:51:57 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/38] 192.168.1.103 () {42 vars in 1312 bytes} [Wed Jan 27 17:52:10 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/39] 192.168.1.103 () {42 vars in 1240 bytes} [Wed Jan 27 17:52:10 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/40] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 17:52:48 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7144|app: -1|req: -1/41] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 17:52:48 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 27 17:57:37 2021] ***
compiled with version: 9.3.0 on 09 January 2021 18:38:09
os: Linux-5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/yusheng/anaconda3/envs/hus38_env/blog
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
your processes number limit is 12600
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
Set PythonHome to /home/yusheng/anaconda3/envs/hus38_env/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x561774104750
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./blogproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'blogproject.settings.production'; 'blogproject.settings' is not a package
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7822)
spawned uWSGI worker 1 (pid: 7824, cores: 1)
spawned uWSGI worker 2 (pid: 7825, cores: 1)
spawned uWSGI worker 3 (pid: 7826, cores: 1)
spawned uWSGI worker 4 (pid: 7827, cores: 1)
spawned uWSGI worker 5 (pid: 7828, cores: 1)
spawned uWSGI worker 6 (pid: 7829, cores: 1)
spawned uWSGI worker 7 (pid: 7830, cores: 1)
spawned uWSGI worker 8 (pid: 7831, cores: 1)
spawned uWSGI worker 9 (pid: 7832, cores: 1)
spawned uWSGI worker 10 (pid: 7833, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/1] 192.168.1.103 () {44 vars in 1314 bytes} [Wed Jan 27 17:57:58 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/2] 192.168.1.103 () {42 vars in 1229 bytes} [Wed Jan 27 17:57:58 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/3] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 17:58:01 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/4] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 17:58:01 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/5] 192.168.1.103 () {46 vars in 1343 bytes} [Wed Jan 27 17:58:02 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/6] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 17:58:02 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/7] 192.168.1.103 () {46 vars in 1343 bytes} [Wed Jan 27 17:58:02 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/8] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 17:58:02 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/9] 192.168.1.103 () {46 vars in 1343 bytes} [Wed Jan 27 17:58:02 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/10] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 17:58:02 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/11] 192.168.1.103 () {46 vars in 1343 bytes} [Wed Jan 27 17:58:03 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/12] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 17:58:03 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/13] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 18:08:30 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/14] 192.168.1.103 () {46 vars in 1282 bytes} [Wed Jan 27 18:08:30 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/15] 192.168.1.103 () {44 vars in 1321 bytes} [Wed Jan 27 18:08:34 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7833|app: -1|req: -1/16] 192.168.1.103 () {42 vars in 1229 bytes} [Wed Jan 27 18:08:34 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Wed Jan 27 18:09:28 2021 - uWSGI worker 10 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Jan 28 02:53:13 2021] ***
compiled with version: 9.3.0 on 09 January 2021 18:38:09
os: Linux-5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/yusheng/anaconda3/envs/hus38_env/blog
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yusheng/anaconda3/envs/hus38_env/blog
your processes number limit is 12600
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
Set PythonHome to /home/yusheng/anaconda3/envs/hus38_env/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55d7a9c5f770
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./blogproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./blogproject/settings/production.py", line 3, in <module>
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
  File "/home/yusheng/anaconda3/envs/hus38_env/lib/python3.8/os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'DJANGO_SECRET_KEY'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10132)
spawned uWSGI worker 1 (pid: 10134, cores: 1)
spawned uWSGI worker 2 (pid: 10135, cores: 1)
spawned uWSGI worker 3 (pid: 10136, cores: 1)
spawned uWSGI worker 4 (pid: 10137, cores: 1)
spawned uWSGI worker 5 (pid: 10138, cores: 1)
spawned uWSGI worker 6 (pid: 10139, cores: 1)
spawned uWSGI worker 7 (pid: 10140, cores: 1)
spawned uWSGI worker 8 (pid: 10141, cores: 1)
spawned uWSGI worker 9 (pid: 10142, cores: 1)
spawned uWSGI worker 10 (pid: 10143, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 10141|app: -1|req: -1/1] 192.168.1.103 () {42 vars in 1290 bytes} [Thu Jan 28 02:53:59 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10143|app: -1|req: -1/2] 192.168.1.103 () {42 vars in 1229 bytes} [Thu Jan 28 02:53:59 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10141|app: -1|req: -1/3] 192.168.1.103 () {44 vars in 1321 bytes} [Thu Jan 28 03:05:11 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10141|app: -1|req: -1/4] 192.168.1.103 () {46 vars in 1282 bytes} [Thu Jan 28 03:05:11 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10141|app: -1|req: -1/5] 192.168.1.103 () {34 vars in 393 bytes} [Fri Jan 29 02:06:50 2021] OPTIONS / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
